import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { FlatCompat } from '@eslint/eslintrc';

/*
 * eslint-config-next 15 still ships eslintrc-style configs, so they are bridged
 * into flat config via FlatCompat. `next lint` is deprecated ahead of Next 16;
 * the `lint` script calls the ESLint CLI directly instead.
 */
const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      '.next/**',
      // Build output: the static export, and the scratch area build-pages.mjs
      // uses while server-only routes are moved aside.
      'out/**',
      '.pages-build-stash/**',
      'node_modules/**',
      'legacy/**',
      'lib/db/migrations/**',
      // Generated by Next.js on every build; not ours to satisfy.
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Deliberate: several catch blocks swallow errors where recovering
      // matters more than reporting (audit writes, hold releases). Each is
      // commented at the site.
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
];

export default config;
